### ISSUE TITLE
Feature Request: Temporary Containers

### ISSUE THREAD

**Issue by EstherMoellman** [jingyu9575/tabs-to-bookmark-groups#7]
@jingyu9575 ,

I understand you're not fan of including other functions inside TabsToBookmarkGroups (TTBG).
But I'm not a fan of having lot of add-ons. And from my point of view, Temporary Containers (TC) is a must for every tab. So in this sense, IMO TC should be part of TTBG.

After very long debates, I was able to convince other Dev's to include TC inside their add-ons. And I really hope to do same with you. So please, here is my first request: To create an option inside TTBG, allowing to always open tabs in TCs on defined groups.

If you don't agree, or don't want to do that, or you haven't time, whatever... I totally respect that!, it'll perfectly fine. In this case, please I ask you a favor: To take a look to these two add-ons below, and to tell me in your opinion which one seems better to you, as a companion for TTBG.

Thank you in advance!

https://addons.mozilla.org/en-US/firefox/addon/confiner/

https://addons.mozilla.org/en-US/firefox/addon/tabcontainer/

PS: These two add-on are the simplest and lightweight I could find.

**Comment by jingyu9575** [comment]
> I understand you're not fan of including other functions inside TabsToBookmarkGroups

Yes, I still hold the idea of *separation of concerns*.

What's the problem with installing both this extension and Temporary Containers? I don't think there are conflicts if "automatic mode" is enabled.

> addons.mozilla.org/en-US/firefox/addon/confiner
> addons.mozilla.org/en-US/firefox/addon/tabcontainer

Both these extensions are using the same method: When a network request happens in a tab, create a new container, open the same URL in a new tab within the container, and close the original tab. I think Temporary Containers is also using this method. All the 3 extensions are free software (open source). 

Therefore I think all are fine and you can just choose one based on the features.

**Comment by jingyu9575** [comment]
If security is your concern, here are some code review information [from jscher2000's search tool](https://www.jeffersonscher.com/sumo/extensions.php):

*Temporary Containers* is not reviewed yet.
*Ephemeral or Confined Container* is not reviewed yet.
*tabContainer* is reviewed on 2019-11-19 (version 1.0.0).

From my experience, smaller extensions are more likely to be reviewed, since reviewers are volunteers. Two of my larger extensions *Select After Closing Current* and *Multithreaded Download Manager* are also not reviewed.

**Comment by EstherMoellman** [comment]
@jingyu9575 , thank you for your answer and for your explanation.
I asked you about the two TC' add-ons, not just concerned on security, but more concerned in compatibility with your TTBG. I was looking for the lightweight and more compatible TC' add-on for working along side with you TTBG.
Thank you again!
PS: Feel free to close the issue, if you want.

**Comment by jingyu9575** [comment]
> more concerned in compatibility with your TTBG

I haven't found any incompatibilities. All the extensions use the same method.
