### ISSUE TITLE
Request: Change icon color at NavBar, identifying group

### ISSUE THREAD

**Issue by EstherMoellman** [jingyu9575/tabs-to-bookmark-groups#8]
@jingyu9575 ,

My friend, please, if doable, I would like to request the following: A color to identify each group, in such way that TTBG' icon at NavBar/ToolBar/etc will show the color of the selected group.

Thank you!

PS: SimpleTabGroups add-on has this function, and is very useful, because users can quickly identify groups just by seeing the color of the icon.

**Comment by jingyu9575** [comment]
We need extension storage to save the groups color, otherwise they change on browser restart.

You see, with the restriction of not using extension storage, everything is difficult...

Workarounds:
1. Prepend symbols to title: ⚫🔵⚪🔴🟠🟣🟤🟡🟢
2. If we choose the *Metadata* approach in #14, save it there.

**Comment by EstherMoellman** [comment]
How exactly "1. Prepend symbols to title" will work? Where this colored circles will appear?

**Comment by jingyu9575** [comment]
Probably this:

![图片](https://user-images.githubusercontent.com/8923139/73954992-eb9e3e00-4902-11ea-944d-6e7dc9dc7ba1.png)

It only needs to be stored in the bookmarks. In the extensions, we can change the icon, so we do not need to display the circles.

**Comment by jingyu9575** [comment]
Which do you think is better, circle or square?
🔵🔴🟠🟣🟤🟡🟢    🟦🟥🟧🟪🟫🟨🟩

![circle](https://user-images.githubusercontent.com/8923139/73954992-eb9e3e00-4902-11ea-944d-6e7dc9dc7ba1.png)

![square](https://user-images.githubusercontent.com/8923139/74249808-0d743800-4cea-11ea-8bb5-04a2f1c5d5e6.png)

**Comment by EstherMoellman** [comment]
Hi @jingyu9575 ! Circles seems to me a bit nicer, but both icons are fine. : )

**Comment by jingyu9575** [comment]
Try the latest build. Color can now be manually set by right-click, or by the option *automatically set a color for every new group*. However the toolbar icon does not show the color yet. 

I think there is some color contrast issues, especially with the dark theme.

**Comment by EstherMoellman** [comment]
Very nice!
Everything seems to works perfect.
The right click also is very nice, allowing to change colors.
Everything is almost perfect.
Congrats and thank you.

I'm saying "almost", because we need the most important color identification: Toolbar icon.
I understand you're experiencing troubles with contrast + dark theme. Two ideas:

1) Can you steal icon system color from [SimpleTabGroups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/)? At this add-on icon colors works perfect under dark theme.

2) If you can not use SimpleTabGroups' icon color system, and you also can not find another solution for coloring toolbar icon under dark theme and contrast... what about an icon badge with colors? If it is not possible icon badge with colors, in the worst case we can replace all the group color system with numbers, identifying groups not by colors, but by numbers... it has the same practical function! Both, colors or numbers, can identify groups. And if you use numbers (instead colors), you can use an icon badge with numbers... like [PowerTabs](https://addons.mozilla.org/pt-BR/firefox/addon/power-tabs/) does.

**Comment by jingyu9575** [comment]
I've manually tuned the colors, but I'm unable to get enough contrast for red, orange, yellow and brown. I think I'd remove brown and only keep 6 primitive colors here, unless someone can design the contrast better.

![图片](https://user-images.githubusercontent.com/8923139/74293864-6967ac80-4d3c-11ea-896f-4814afb2a9c4.png)

**Comment by EstherMoellman** [comment]
Perfect! : )

**Comment by EstherMoellman** [comment]
... just two more minor comments:
1) I believe you also can keep the original "white" (light theme) and "black" (dark theme) icon colors, for those users that don't want colors.
2) If by chance you can fill inside the icon with the group color, IMHO it will be nicer. I don't mean the icon background, just inside the icon.

**Comment by jingyu9575** [comment]
1. Right-click, set color, none. The extension won't generate any color if the option *automatically set a color* is not enabled.
2. Then it will look like the picture below. I'm not sure whether this is better...
![图片](https://user-images.githubusercontent.com/8923139/74335652-f3dff880-4d9c-11ea-8bec-33235d121fd7.png)

**Comment by EstherMoellman** [comment]
1) Icon colors: ABSOLUTELY F-A-N-T-A-S-T-I-C! Perfect. Very nice. Hope they will have same nice look also at dark theme. But when I talked about "to fill", I meant the icon at toolbar, not at popup. Any chance to fill the icon at NabBar/Toolbar with the colors?

2) White/Black: I understand these two colors are going to work if users choose "set color none". But I still believe white/black (as primary colors) also may be useful if users want to identify groups by colors. However, the last word always is yours. Up to you. Personally, I think is already perfect what you did.

**Comment by jingyu9575** [comment]
Now the icon can be selected in the options. `3` is the filled icon.

> white/black (as primary colors) also may be useful if users want to identify groups by colors

If the browser has the light theme, white won't be visible, and black will be the same as "none". The opposite happens if the dark theme is used. So I think white/black colors are difficult to use.

**Comment by EstherMoellman** [comment]
@jingyu9575 ... P-E-R-F-E-C-T AND O-U-T-S-T-A-N-D-I-N-G!... over-exceeded all expectations... beautiful and functional feature. I'm speechless. I just can say: Thank you and congrats.
