### ISSUE TITLE
Request: Dark theme for icon popup 

### ISSUE THREAD

**Issue by EstherMoellman** [jingyu9575/tabs-to-bookmark-groups#9]
@jingyu9575 , please, if possible, it will be nice a dark theme for the icon popup. Thank you!

**Comment by jingyu9575** [comment]
The option is added, although I'm not good at designing. It is just copied from Onurtag's contribution to *Multithreaded Download Manager*.

**Comment by EstherMoellman** [comment]
Thank you!
It has not need to be perfect at all.
A kind of basic simple "background: #202020; color: white"... will be enough.
And considering that TTBG now has its specific support at SideBar, I believe same "background: #202020; color: white" will be useful too.
